let default_decks = [
	// Lyria & Rivia Decks (2)
	{
		"title": "Lyria & Rivia - Muster & Shield",
		"description": "Focus on muster units and shield mechanics",
		"leader": "lr_meve_princess",
		"faction": "lyria_rivia",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 2],
			["spe_scorch", 1],
			["spe_clear", 1],
			["spe_frost", 1],
			["lr_gascon", 1],
			["lr_gascon_light_cavalry", 1],
			["lr_gascon_slinger", 1],
			["lr_gascon_infiltrator", 1],
			["lr_landsknecht", 3],
			["lr_grey_rider", 2],
			["lr_light_cavalry", 2],
			["lr_wagenburg", 3],
			["lr_knighthood", 1],
			["lr_grenadiers", 2],
			["lr_prince_anseis", 1],
			["lr_reynard_odo", 1],
			["lr_royal_guard", 1],
			["lr_rivian_mauler", 1],
			["lr_pikeman", 2],
			["ntr_ciri", 1]
		]
	},
	{
		"title": "Lyria & Rivia - Scorch & Guard",
		"description": "Focus on unique scorch_s and guard units",
		"leader": "lr_meve_resolute",
		"faction": "lyria_rivia",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 2],
			["spe_scorch", 2],
			["spe_clear", 1],
			["spe_fog", 1],
			["lr_knighthood", 1],
			["lr_grenadiers", 2],
			["lr_war_wagon", 1],
			["lr_wagenburg", 2],
			["lr_prince_anseis", 1],
			["lr_reynard_odo", 1],
			["lr_royal_guard", 1],
			["lr_rivian_mauler", 1],
			["lr_pikeman", 3],
			["lr_landsknecht", 2],
			["lr_grey_rider", 2],
			["lr_light_cavalry", 2],
			["ntr_ciri", 1],
			["ntr_yennefer", 1]
		]
	},
	// Monsters Decks (3)
	{
		"title": "Monsters - Swarm & Muster",
		"description": "Focus on swarms and muster mechanics",
		"leader": "mo_eredin_commander",
		"faction": "monsters",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 2],
			["spe_scorch", 1],
			["spe_clear", 1],
			["spe_fog", 1],
			["mo_arachas_behemoth", 1],
			["mo_arachas", 1],
			["mo_arachas_1", 1],
			["mo_arachas_2", 1],
			["mo_nekker", 1],
			["mo_nekker_1", 1],
			["mo_nekker_2", 1],
			["mo_witch_velen", 1],
			["mo_witch_velen_1", 1],
			["mo_witch_velen_2", 1],
			["mo_ghoul", 1],
			["mo_ghoul_1", 1],
			["mo_ghoul_2", 1],
			["mo_imlerith", 1],
			["mo_kayran", 1],
			["mo_katakan", 1],
			["mo_bruxa", 1],
			["mo_fleder", 1],
			["ntr_ciri", 1]
		]
	},
	{
		"title": "Monsters - Wild Hunt",
		"description": "Focus on Wild Hunt units and giants",
		"leader": "mo_eredin_bringer_of_death",
		"faction": "monsters",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 1],
			["spe_scorch", 2],
			["spe_clear", 1],
			["spe_frost", 2],
			["mo_imlerith", 1],
			["mo_caranthir", 1],
			["mo_nithral", 1],
			["mo_wild_hunt_rider_1", 1],
			["mo_wild_hunt_rider_2", 1],
			["mo_wild_hunt_rider_3", 1],
			["mo_navigator", 1],
			["mo_jotunn", 1],
			["mo_frost_giant", 1],
			["mo_cyclops", 1],
			["mo_ice_troll", 1],
			["mo_old_speartip", 1],
			["mo_gaunter", 1],
			["mo_gaunter_odimm_darkness", 2],
			["mo_kayran", 1],
			["mo_earth_elemental", 1],
			["mo_fire_elemental", 1],
			["ntr_ciri", 1]
		]
	},
	{
		"title": "Monsters - Necromancy & Curse",
		"description": "Focus on sacrifice, necromancy, and curse abilities",
		"leader": "mo_eredin_commander",
		"faction": "monsters",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 2],
			["spe_scorch", 1],
			["spe_clear", 1],
			["spe_rain", 1],
			["mo_toad", 1],
			["mo_botchling", 1],
			["mo_katakan", 1],
			["mo_bruxa", 1],
			["mo_ekkima", 1],
			["mo_fleder", 1],
			["mo_garkain", 1],
			["mo_lamia_1", 1],
			["mo_lamia_2", 1],
			["mo_lamia_3", 1],
			["mo_alghoul", 1],
			["mo_archgriffin", 1],
			["mo_alp", 1],
			["mo_leshen", 1],
			["mo_manticore", 1],
			["mo_manticore_venom", 1],
			["mo_dragon_fyresdal", 1],
			["mo_glustyworp", 1],
			["ntr_ciri", 1],
			["ntr_yennefer", 1]
		]
	},
	// Nilfgaard Decks (3)
	{
		"title": "Nilfgaard - Spies & Conspiracy",
		"description": "Focus on cheap spies and conspiracy abilities",
		"leader": "ne_emhyr_relentless",
		"faction": "nilfgaard",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 3],
			["spe_scorch", 1],
			["spe_clear", 1],
			["spe_fog", 1],
			["ne_stefan", 1],
			["ne_sweers", 1],
			["ne_usurper", 1],
			["ne_shilard", 1],
			["ne_vattier", 1],
			["ne_young_emissary_1", 1],
			["ne_young_emissary_2", 1],
			["ne_emissary", 1],
			["ne_cantarella", 1],
			["ne_ardal_aep_dahy", 1],
			["ne_impera_brigade_1", 1],
			["ne_impera_brigade_2", 1],
			["ne_impera_brigade_3", 1],
			["ne_impera_brigade_4", 1],
			["ne_archer_support", 1],
			["ne_archer_support_1", 1],
			["ne_siege_support", 1],
			["ne_menagerie_keeper", 1],
			["ntr_ciri", 1]
		]
	},
	{
		"title": "Nilfgaard - Army & Muster",
		"description": "Focus on army units and muster mechanics",
		"leader": "ne_emhyr_emperor",
		"faction": "nilfgaard",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 2],
			["spe_scorch", 1],
			["spe_clear", 1],
			["spe_rain", 1],
			["ne_black_archer", 1],
			["ne_black_archer_1", 1],
			["ne_heavy_zerri", 1],
			["ne_menno", 1],
			["ne_moorvran", 1],
			["ne_tibor", 1],
			["ne_nauzicaa_1", 1],
			["ne_nauzicaa_2", 1],
			["ne_nauzicaa_3", 1],
			["ne_nausicaa_brigade", 1],
			["ne_ard_feainn_light_cavalry", 3],
			["ne_ard_feainn_tortoise", 3],
			["ne_impera_brigade_1", 1],
			["ne_impera_brigade_2", 1],
			["ne_standard_bearer", 1],
			["ne_nausicaa_standard_bearer", 1],
			["ntr_ciri", 1]
		]
	},
	{
		"title": "Nilfgaard - Nobility & Espionage",
		"description": "Focus on nobility and espionage tactics",
		"leader": "ne_emhyr_whiteflame",
		"faction": "nilfgaard",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 2],
			["spe_scorch", 2],
			["spe_clear", 1],
			["spe_fog", 1],
			["ne_jan_calveit", 1],
			["ne_vattier", 1],
			["ne_cantarella", 1],
			["ne_assire", 1],
			["ne_fringilla", 1],
			["ne_cahir", 1],
			["ne_peter_saar_gwynleve", 1],
			["ne_renuald", 1],
			["ne_guardian", 1],
			["ne_knight", 1],
			["ne_impera_brigade_1", 1],
			["ne_impera_brigade_2", 1],
			["ne_impera_brigade_3", 1],
			["ne_impera_brigade_4", 1],
			["ne_impera_brigade_5", 1],
			["ne_diplomat", 1],
			["spe_treason", 1],
			["ne_infiltrator", 1],
			["ntr_ciri", 1],
			["ntr_yennefer", 1]
		]
	},
	// Northern Realms Decks (3)
	{
		"title": "Northern Realms - Veteran & Fortify",
		"description": "Focus on veteran and fortify abilities",
		"leader": "nr_foltest_siegemaster",
		"faction": "realms",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 2],
			["spe_scorch", 1],
			["spe_clear", 1],
			["spe_frost", 1],
			["nr_peace_treaty", 1],
			["nr_esterad", 1],
			["nr_natalis", 1],
			["nr_philippa", 1],
			["nr_vernon", 1],
			["nr_stennis", 1],
			["nr_catapult_1", 1],
			["nr_catapult_2", 1],
			["nr_ballista", 1],
			["nr_siege_tower", 1],
			["nr_trebuchet", 1],
			["nr_trebuchet_1", 1],
			["nr_crinfrid_1", 1],
			["nr_crinfrid_2", 1],
			["nr_crinfrid_3", 1],
			["nr_banner_nurse", 1],
			["nr_blue_stripes_1", 1],
			["nr_blue_stripes_2", 1],
			["nr_blue_stripes_3", 1],
			["nr_dijkstra", 1],
			["nr_thaler", 1],
			["ntr_ciri", 1]
		]
	},
	{
		"title": "Northern Realms - Siege & Morale",
		"description": "Focus on siege units and morale boosts",
		"leader": "nr_foltest_lord",
		"faction": "realms",
		"cards": [
			["spe_horn", 2],
			["spe_decoy", 2],
			["spe_scorch", 1],
			["spe_clear", 1],
			["spe_rain", 1],
			["nr_peace_treaty", 1],
			["nr_henselt", 1],
			["nr_demavend", 1],
			["nr_kaedweni_siege_support_1", 1],
			["nr_kaedweni_siege_support_2", 1],
			["nr_catapult_1", 1],
			["nr_catapult_2", 1],
			["nr_reinforced_ballista_1", 1],
			["nr_reinforced_ballista_2", 1],
			["nr_reinforced_trebuchet_1", 1],
			["nr_reinforced_trebuchet_2", 1],
			["nr_banner_nurse", 1],
			["nr_ban_ard_tutor", 1],
			["nr_kaedweni_knight", 1],
			["nr_dun_banner_heavy_cavalry_1", 1],
			["nr_dun_banner_heavy_cavalry_2", 1],
			["nr_odrin", 1],
			["nr_seltkirk", 1],
			["nr_kaedweni_sergeant", 1],
			["ntr_ciri", 1],
			["ntr_yennefer", 1]
		]
	},
	{
		"title": "Northern Realms - Temeria & Bond",
		"description": "Focus on Temerian cards and tight bond",
		"leader": "nr_foltest_commander",
		"faction": "realms",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 2],
			["spe_scorch", 1],
			["spe_clear", 1],
			["spe_fog", 1],
			["nr_peace_treaty", 1],
			["nr_esterad", 1],
			["nr_natalis", 1],
			["nr_vernon", 1],
			["nr_blue_stripes_skirmisher_1", 1],
			["nr_blue_stripes_skirmisher_2", 1],
			["nr_blue_stripes_skirmisher_3", 1],
			["nr_blue_stripes_1", 1],
			["nr_blue_stripes_2", 1],
			["nr_blue_stripes_3", 1],
			["nr_dijkstra", 1],
			["nr_thaler", 1],
			["nr_temerian_soldier_1", 1],
			["nr_temerian_soldier_2", 1],
			["nr_temerian_soldier_3", 1],
			["nr_stripes_scout", 1],
			["nr_temerian_drummer", 1],
			["nr_foltest_pride", 1],
			["nr_temerian_knight", 1],
			["ntr_ciri", 1],
			["ntr_dandelion", 1]
		]
	},
	// Ofir Decks (2)
	{
		"title": "Ofir - Trade & Adaptive",
		"description": "Focus on trade and adaptive abilities",
		"leader": "ofir_king_of_ofir",
		"faction": "ofir",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 2],
			["spe_scorch", 1],
			["spe_clear", 1],
			["spe_sandstorm", 2],
			["ofir_dulla", 1],
			["ofir_slave_trader", 2],
			["ofir_courtesan", 1],
			["ofir_merchant", 1],
			["ofir_adaptive_unit_1", 1],
			["ofir_adaptive_unit_2", 1],
			["ofir_adaptive_unit_3", 1],
			["ofir_runewright", 2],
			["ofir_runestone", 2],
			["ofir_guardian", 1],
			["ofir_warrior", 1],
			["ofir_archer", 1],
			["ofir_siege_engine", 1],
			["ofir_scribe", 2],
			["ntr_ciri", 1]
		]
	},
	{
		"title": "Ofir - Sandstorm & Elements",
		"description": "Focus on sandstorms and overcoming elements",
		"leader": "ofir_sultan",
		"faction": "ofir",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 2],
			["spe_scorch", 1],
			["spe_clear", 1],
			["spe_sandstorm", 3],
			["ofir_dulla", 1],
			["ofir_adaptive_unit_1", 1],
			["ofir_adaptive_unit_2", 1],
			["ofir_adaptive_unit_3", 1],
			["ofir_runewright", 2],
			["ofir_runestone", 2],
			["ofir_guardian", 1],
			["ofir_warrior", 1],
			["ofir_archer", 1],
			["ofir_siege_engine", 1],
			["ofir_merchant", 1],
			["ofir_courtesan", 1],
			["ofir_scribe", 2],
			["ntr_ciri", 1],
			["ntr_yennefer", 1]
		]
	},
	// Scoia'tael Decks (2)
	{
		"title": "Scoia'tael - Waylay & Mobility",
		"description": "Focus on waylay and high mobility units",
		"leader": "sc_francesca_daisy",
		"faction": "scoiatael",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 2],
			["spe_scorch", 1],
			["spe_clear", 1],
			["spe_frost", 1],
			["sc_isengrim", 1],
			["sc_milva", 1],
			["sc_schirru", 1],
			["sc_ciaran", 1],
			["sc_dol_infantry", 1],
			["sc_dol_infantry_1", 1],
			["sc_dol_infantry_2", 1],
			["sc_havekar_support", 1],
			["sc_havekar_support_1", 1],
			["sc_havekar_support_2", 1],
			["sc_havekar_nurse", 1],
			["sc_havekar_nurse_1", 1],
			["sc_dwarf", 1],
			["sc_dwarf_1", 1],
			["sc_dwarf_2", 1],
			["sc_elven_mercenary_1", 1],
			["sc_elven_mercenary_2", 1],
			["sc_vrihedd_sapper", 1],
			["ntr_ciri", 1],
			["ntr_dandelion", 1]
		]
	},
	{
		"title": "Scoia'tael - Guards & Muster",
		"description": "Focus on dwarven guards and muster",
		"leader": "sc_francesca_hope_of_the_aen_seidhe",
		"faction": "scoiatael",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 2],
			["spe_scorch", 1],
			["spe_clear", 1],
			["spe_fog", 1],
			["sc_isengrim", 1],
			["sc_milva", 1],
			["sc_filavandrel", 1],
			["sc_brouver_hoog", 1],
			["sc_barclay", 1],
			["sc_dol_blathanna_guard_1", 1],
			["sc_dol_blathanna_guard_2", 1],
			["sc_dol_blathanna_guard_3", 1],
			["sc_mahakam_guard_1", 1],
			["sc_mahakam_guard_2", 1],
			["sc_vrihedd_dragoon_1", 1],
			["sc_vrihedd_dragoon_2", 1],
			["sc_vrihedd_dragoon_3", 1],
			["sc_vrihedd_brigade", 1],
			["sc_vrihedd_brigade_1", 1],
			["sc_aelirenn", 1],
			["sc_dryads_1", 1],
			["sc_dryads_2", 1],
			["sc_dryads_3", 1],
			["ntr_ciri", 1]
		]
	},
	// Skellige Decks (2)
	{
		"title": "Skellige - Berserkers & Avenger",
		"description": "Focus on berserkers and avenger mechanics",
		"leader": "sk_crach_an_craite",
		"faction": "skellige",
		"cards": [
			["spe_horn", 1],
			["spe_mardroeme", 1],
			["spe_scorch", 1],
			["spe_storm", 1],
			["spe_rain", 1],
			["sk_olaf", 1],
			["sk_cerys", 1],
			["sk_ermion", 1],
			["sk_hjalmar", 1],
			["sk_young_berserker", 3],
			["sk_berserker", 1],
			["sk_drummond_berserker", 1],
			["sk_chosen_berserker", 1],
			["sk_craite_warrior_1", 1],
			["sk_craite_warrior_2", 1],
			["sk_craite_warrior_3", 1],
			["sk_shield_maiden_1", 1],
			["sk_shield_maiden_2", 1],
			["sk_shield_maiden_3", 1],
			["sk_light_longship", 3],
			["sk_birna", 1],
			["sk_kambi", 1],
			["ntr_ciri", 1]
		]
	},
	{
		"title": "Skellige - Tactics & Storms",
		"description": "Focus on tactics and storm mechanics",
		"leader": "sk_king_bran",
		"faction": "skellige",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 2],
			["spe_storm", 2],
			["spe_clear", 1],
			["spe_frost", 1],
			["sk_olaf", 1],
			["sk_cerys", 1],
			["sk_birna", 1],
			["sk_war_longship_1", 1],
			["sk_war_longship_2", 1],
			["sk_light_longship", 3],
			["sk_dimun_pirate", 1],
			["sk_dimun_pirate_captain", 1],
			["sk_tuirseach_warrior_1", 1],
			["sk_tuirseach_warrior_2", 1],
			["sk_brokva_archer", 2],
			["sk_eist_tuirseach", 1],
			["sk_skellige_fleet_1", 1],
			["sk_skellige_fleet_2", 1],
			["sk_skellige_fleet_3", 1],
			["sk_arnjolf", 1],
			["ntr_ciri", 1]
		]
	},
	// Syndicate Decks (2)
	{
		"title": "Syndicate - Execute & Bank",
		"description": "Focus on execute and bank mechanics",
		"leader": "sy_carlo_varese",
		"faction": "syndicate",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 2],
			["spe_scorch", 1],
			["spe_clear", 1],
			["spe_dimeritium_shackles", 2],
			["sy_sigi_reuven", 1],
			["sy_doadrick", 1],
			["sy_flaming_rose_footman", 1],
			["sy_bare_knuckle_brawler", 1],
			["sy_witch_hunter_1", 1],
			["sy_witch_hunter_2", 1],
			["sy_witch_hunter_3", 1],
			["sy_executioner_1", 1],
			["sy_executioner_2", 1],
			["sy_executioner_3", 1],
			["sy_bank_card", 1],
			["sy_tax_collector", 1],
			["sy_coin_master", 1],
			["sy_thug", 1],
			["sy_cutthroat", 1],
			["sy_fence", 1],
			["sy_swindler", 1],
			["ntr_ciri", 1]
		]
	},
	{
		"title": "Syndicate - Witch Hunters",
		"description": "Focus on witch hunters and syndicate units",
		"leader": "sy_francis_bedlam",
		"faction": "syndicate",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 2],
			["spe_scorch", 1],
			["spe_clear", 1],
			["spe_dimeritium_shackles", 3],
			["sy_sigi_reuven", 1],
			["sy_cyprian_wiley", 1],
			["sy_doadrick", 1],
			["sy_witch_hunter_1", 1],
			["sy_witch_hunter_2", 1],
			["sy_witch_hunter_3", 1],
			["sy_executioner_1", 1],
			["sy_executioner_2", 1],
			["sy_executioner_3", 1],
			["sy_flaming_rose_footman", 1],
			["sy_bare_knuckle_brawler", 1],
			["sy_thug", 1],
			["sy_cutthroat", 1],
			["sy_fence", 1],
			["sy_swindler", 1],
			["sy_tax_collector", 1],
			["sy_coin_master", 1],
			["ntr_ciri", 1],
			["ntr_yennefer", 1]
		]
	},
	// Toussaint Decks (2)
	{
		"title": "Toussaint - Nightfall & Wine",
		"description": "Focus on nightfall and wine abilities",
		"leader": "to_anna_henrietta",
		"faction": "toussaint",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 2],
			["spe_scorch", 1],
			["spe_clear", 1],
			["spe_nightfall", 3],
			["to_anna_henrietta_duchess", 1],
			["to_damien", 1],
			["to_palmerin", 1],
			["to_vivienne", 1],
			["to_wine_card_1", 1],
			["to_wine_card_2", 1],
			["to_wine_card_3", 1],
			["to_hunger_unit_1", 1],
			["to_hunger_unit_2", 1],
			["to_knight_1", 1],
			["to_knight_2", 1],
			["to_guard_1", 1],
			["to_guard_2", 1],
			["to_archer", 1],
			["to_siege", 1],
			["ntr_ciri", 1]
		]
	},
	{
		"title": "Toussaint - Vampires & Hunger",
		"description": "Focus on vampires and hunger mechanics",
		"leader": "to_dettlaff",
		"faction": "toussaint",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 2],
			["spe_scorch", 1],
			["spe_clear", 1],
			["spe_nightfall", 3],
			["to_dettlaff", 1],
			["to_regis", 1],
			["to_orianna", 1],
			["to_hunger_unit_1", 1],
			["to_hunger_unit_2", 1],
			["to_hunger_unit_3", 1],
			["to_vampire_1", 1],
			["to_vampire_2", 1],
			["to_vampire_3", 1],
			["to_wine_card_1", 1],
			["to_wine_card_2", 1],
			["to_knight_1", 1],
			["to_knight_2", 1],
			["to_guard_1", 1],
			["to_archer", 1],
			["ntr_ciri", 1],
			["ntr_yennefer", 1]
		]
	},
	// Witcher Universe Deck (1)
	{
		"title": "Witcher Universe - Heroes & Signs",
		"description": "Focus on strong heroes and unique signs",
		"leader": "wu_vilgefortz_sorcerer",
		"faction": "witcher_universe",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 2],
			["spe_scorch", 1],
			["spe_clear", 1],
			["spe_sign_igni", 2],
			["spe_sign_quen", 2],
			["spe_sign_axii", 2],
			["spe_sign_aard", 2],
			["spe_sign_yrden", 2],
			["wu_geralt_1", 1],
			["wu_vesemir", 1],
			["wu_lambert", 1],
			["wu_eskel", 1],
			["wu_coen", 1],
			["wu_ivar", 1],
			["wu_gezras", 1],
			["wu_gaetan", 1],
			["wu_brehen", 1],
			["wu_arnaghad", 1],
			["wu_letho", 1],
			["wu_tissaia", 1],
			["wu_coral", 1],
			["ntr_ciri", 1],
			["ntr_yennefer", 1]
		]
	}
];

var custom_decks = [];

var premade_deck = default_decks;

var deckWeightConsts = {
	"spyBase": 20,
	"heroMult": 2,
	"musterMult": 2,
	"tightBondMult": 2,
	"medic": 7,
	"scorch": 5,
	"scorch_c": 5,
	"morale": 5,
	"agile": 2,
	"horn": 10,
	"berserker": 5,
	"mardroeme": 5,
	"avenger": 5,
	"decoy": 7,
	"clearWeatherWeight": 7,
	"heroSpyBase": 5,
	"cintra_slaughter": 5,
	"resilience": 5,
	"witcherSchoolWeight": 1,
	"witch_hunt": 5,
	"worshipper": 2,
	"worshipped": 2,
	"inspire": 3
};

function calcDeckWeight(deck) {
	var total = 0;
	deck.cards.forEach(entry => {
		let c = card_dict[entry[0]];
		let cnt = parseInt(entry[1]);
		let abi = c["ability"].split(" ");
		let cStr = 0;
		if (!c["deck"].startsWith("special") && !c["deck"].startsWith("weather")) {
			if (abi.includes("spy")) {
				cStr = deckWeightConsts["spyBase"] - parseInt(c["strength"]);
				if (abi.includes("hero")) cStr += deckWeightConsts["heroSpyBase"];
				if (c.row === "agile") cStr += deckWeightConsts["agile"];
			} else {
				cStr = parseInt(c["strength"]);
				if (abi.includes("hero")) cStr *= deckWeightConsts["heroMult"];
				if (abi.includes("bond")) cStr *= deckWeightConsts["tightBondMult"];
				if (abi.includes("muster")) cStr *= deckWeightConsts["musterMult"];
				abi.forEach(a => {
					if (a in deckWeightConsts) cStr += deckWeightConsts[a];
				});
				if (
					abi.includes("witcher_wolf_school") ||
					abi.includes("witcher_bear_school") ||
					abi.includes("witcher_viper_school") ||
					abi.includes("witcher_cat_school") ||
					abi.includes("witcher_griffin_school")
				) cStr += deckWeightConsts["witcherSchoolWeight"];
				if (c.row === "agile") cStr += deckWeightConsts["agile"];
			}
		}
		total += (cStr*cnt);
	});
	return total;
}
